server:
  port: 8189
  servlet:
    context-path: /api/v1/app
#  servlet:
#    session:
#      timeout: 60s
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tournamentDB
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
  flyway:
    url: jdbc:h2:mem:tournamentDB
    user: sa
    password:
